// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WWN.Infrastructure.Persistence;

#nullable disable

namespace WWN.Infrastructure.Migrations
{
    [DbContext(typeof(WwnDbContext))]
    partial class WwnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("WWN.Domain.Aggregates.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Background")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartialClassA")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartialClassB")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpellSlotsUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("WWN.Domain.Entities.CharacterAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterAttributes", (string)null);
                });

            modelBuilder.Entity("WWN.Domain.Entities.CharacterSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSkills", (string)null);
                });

            modelBuilder.Entity("WWN.Domain.Entities.ClassAbilityDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassOwner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ClassOwner");

                    b.ToTable("ClassAbilityDefinitions", (string)null);
                });

            modelBuilder.Entity("WWN.Domain.Entities.Focus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConditionalActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Foci", (string)null);
                });

            modelBuilder.Entity("WWN.Domain.Entities.FocusDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanTakeMultipleTimes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasLevel2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level1Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level2Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FocusDefinitions", (string)null);
                });

            modelBuilder.Entity("WWN.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Encumbrance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Items", (string)null);

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WWN.Domain.Entities.KnownSpell", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SpellId");

                    b.ToTable("KnownSpells", (string)null);
                });

            modelBuilder.Entity("WWN.Domain.Entities.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpellLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Spells", (string)null);
                });

            modelBuilder.Entity("WWN.Domain.Entities.Armor", b =>
                {
                    b.HasBaseType("WWN.Domain.Entities.Item");

                    b.Property<int>("AcBonus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AcBonus");

                    b.Property<bool>("IsShield")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsShield");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("WWN.Domain.Entities.Weapon", b =>
                {
                    b.HasBaseType("WWN.Domain.Entities.Item");

                    b.Property<string>("AttributeModifier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CombatSkill")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tags")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("WWN.Domain.Entities.CharacterAttribute", b =>
                {
                    b.HasOne("WWN.Domain.Aggregates.Character", null)
                        .WithMany("Attributes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WWN.Domain.ValueObjects.AttributeScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("CharacterAttributeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Score");

                            b1.HasKey("CharacterAttributeId");

                            b1.ToTable("CharacterAttributes");

                            b1.WithOwner()
                                .HasForeignKey("CharacterAttributeId");
                        });

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("WWN.Domain.Entities.CharacterSkill", b =>
                {
                    b.HasOne("WWN.Domain.Aggregates.Character", null)
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WWN.Domain.ValueObjects.SkillRank", "Rank", b1 =>
                        {
                            b1.Property<Guid>("CharacterSkillId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Level")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Level");

                            b1.HasKey("CharacterSkillId");

                            b1.ToTable("CharacterSkills");

                            b1.WithOwner()
                                .HasForeignKey("CharacterSkillId");
                        });

                    b.Navigation("Rank")
                        .IsRequired();
                });

            modelBuilder.Entity("WWN.Domain.Entities.ClassAbilityDefinition", b =>
                {
                    b.HasOne("WWN.Domain.Aggregates.Character", null)
                        .WithMany("ClassAbilities")
                        .HasForeignKey("CharacterId");

                    b.OwnsMany("WWN.Domain.ValueObjects.ClassAbilityEffect", "Effects", b1 =>
                        {
                            b1.Property<Guid>("ClassAbilityDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Condition")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<int>("NumericValue")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TargetAttribute")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TargetSkill")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ValueType")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ClassAbilityDefinitionId", "Id");

                            b1.ToTable("ClassAbilityDefinitions");

                            b1.ToJson("Effects");

                            b1.WithOwner()
                                .HasForeignKey("ClassAbilityDefinitionId");
                        });

                    b.Navigation("Effects");
                });

            modelBuilder.Entity("WWN.Domain.Entities.Focus", b =>
                {
                    b.HasOne("WWN.Domain.Aggregates.Character", null)
                        .WithMany("Foci")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("WWN.Domain.ValueObjects.FocusEffect", "Effects", b1 =>
                        {
                            b1.Property<Guid>("FocusId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Condition")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<int>("NumericValue")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TargetAttribute")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TargetSkill")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ValueType")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FocusId", "Id");

                            b1.ToTable("Foci");

                            b1.ToJson("Effects");

                            b1.WithOwner()
                                .HasForeignKey("FocusId");
                        });

                    b.Navigation("Effects");
                });

            modelBuilder.Entity("WWN.Domain.Entities.FocusDefinition", b =>
                {
                    b.OwnsMany("WWN.Domain.ValueObjects.FocusEffect", "Level1Effects", b1 =>
                        {
                            b1.Property<Guid>("FocusDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Condition")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<int>("NumericValue")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TargetAttribute")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TargetSkill")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ValueType")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FocusDefinitionId", "Id");

                            b1.ToTable("FocusDefinitions");

                            b1.ToJson("Level1Effects");

                            b1.WithOwner()
                                .HasForeignKey("FocusDefinitionId");
                        });

                    b.OwnsMany("WWN.Domain.ValueObjects.FocusEffect", "Level2Effects", b1 =>
                        {
                            b1.Property<Guid>("FocusDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Condition")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<int>("NumericValue")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TargetAttribute")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("TargetSkill")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ValueType")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FocusDefinitionId", "Id");

                            b1.ToTable("FocusDefinitions");

                            b1.ToJson("Level2Effects");

                            b1.WithOwner()
                                .HasForeignKey("FocusDefinitionId");
                        });

                    b.Navigation("Level1Effects");

                    b.Navigation("Level2Effects");
                });

            modelBuilder.Entity("WWN.Domain.Entities.Item", b =>
                {
                    b.HasOne("WWN.Domain.Aggregates.Character", null)
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WWN.Domain.Entities.KnownSpell", b =>
                {
                    b.HasOne("WWN.Domain.Aggregates.Character", null)
                        .WithMany("Spellbook")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WWN.Domain.Entities.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("WWN.Domain.Entities.Weapon", b =>
                {
                    b.OwnsOne("WWN.Domain.ValueObjects.DamageDie", "DamageDie", b1 =>
                        {
                            b1.Property<Guid>("WeaponId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Count")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DamageDieCount");

                            b1.Property<int>("Sides")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DamageDieSides");

                            b1.HasKey("WeaponId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("WeaponId");
                        });

                    b.OwnsOne("WWN.Domain.ValueObjects.ShockInfo", "Shock", b1 =>
                        {
                            b1.Property<Guid>("WeaponId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("AcThreshold")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ShockAcThreshold");

                            b1.Property<int>("Damage")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ShockDamage");

                            b1.HasKey("WeaponId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("WeaponId");
                        });

                    b.Navigation("DamageDie")
                        .IsRequired();

                    b.Navigation("Shock");
                });

            modelBuilder.Entity("WWN.Domain.Aggregates.Character", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("ClassAbilities");

                    b.Navigation("Foci");

                    b.Navigation("Inventory");

                    b.Navigation("Skills");

                    b.Navigation("Spellbook");
                });
#pragma warning restore 612, 618
        }
    }
}
